### ISSUE TITLE
Add Quarto Support

### ISSUE THREAD

**Issue by pjkreutzer** [ltex-plus/vscode-ltex-plus#63]
Note: Per the contribution guidelines, deleting parts of the template or not filling in vital information may result in the issue to be immediately closed as invalid.

**Is your feature request related to a problem? Please describe.**
Quarto is an open-source scientific and technical publishing system (https://quarto.org/) that allows the combination of code cells and markdown. Essentially it is the successor to RMarkdown but with more extensive support for other languages such as python. Currently using LTeX+ requires the .qmd file to be converted to a .md file, for it to be checked.

**Describe the solution you'd like**
Native checking of the markdown sections in a .qmd file, ideally even checking of code chunks.

**Describe alternatives you've considered**
Manually converting the .qmd file to a .md file makes it checkable by LTeX+, but interrupts the writing flow.

**Additional context**

**Comment by spitzerd** [comment]
ltex-ls-plus already supports Quarto, so activating it in the VS Code extension is no big deal.  You can find further information about this topic here: https://github.com/valentjn/vscode-ltex/issues/699
 
However, I can not give you a timeline when this will be available. Pull requests are welcome, of course.
