### ISSUE TITLE
False positive with glossary command.

### ISSUE THREAD

**Issue by villmow** [ltex-plus/vscode-ltex-plus#64]
I use LTex and it works nicely. However, one false positive in relation to the commands from the glossary package is bogging me. 

**Describe the bug**

For the following sentence:

```tex
I use an \gls{IDE}.
```

LTeX will produce the following error:

```
Use 'a' instead of 'an' if the following word doesn't start with a vowel sound, e.g. 'a sentence', 'a university'.LTeX[EN_A_VS_AN](https://community.languagetool.org/rule/show/EN_A_VS_AN?lang=en-US)
```

It works for:
```tex
I use an \emph{IDE}.
```

Is there a way to set the latex commands that should basically be **removed/stripped** before spell checking? Not just ignoring the inside from spell checking.

**Comment by spitzerd** [comment]
The argument of `\gls{}` is a label. Hence, it could be any kind of string. For example:
```
\newglossaryentry{abitraryString123}{
    name=latex,
    description={A markup language specially suited for scientific documents}
}

The \gls{abitraryString123} typesetting markup language is great.
```
Because it´s a label, LTeX+ replaces the word "abitraryString123" with the word "Dummy".
You can find more information here: https://github.com/valentjn/vscode-ltex/issues/366

Setting `{"ltex.latex.commands": {"\\gls{}": "default"}}` should solve your issue.

**Comment by villmow** [comment]
Thanks, that solves it. I checked the documentation, but couldn't find that information.

**Comment by q-wertz** [comment]
Stumbled into the same problem.

Setting it to `default` removes the `EN_A_VS_AN` error but in case the keyword isn't a correct word instead a spelling mistake is raised.

E.g. for `\acrfull*{adsb}`

Would it be possible to resolve the abbreviation and use this as "dummy word"?
