### ISSUE TITLE
Command to close LTeX 

### ISSUE THREAD

**Issue by pierrebrd** [ltex-plus/vscode-ltex-plus#73]
LTeX is automatically activated when editing a file that triggers it, and the list of files triggering it can't be edited (ltex.enabled allows us to edit the code languages that enable LTeX checking, but even when removing a code language, LTeX will still start)

An interesting feature would be a command to deactivate LTeX when it is not needed, in order to free some RAM (1GB is not insignificant!). Currently, the "LTeX Reset and Restart" command allows us to close LTeX, but it will automatically be started again.

**Comment by spitzerd** [comment]
Done. You can test starting from the next nightly release. The command is called `LTeX: Close LTeX+`

**Comment by pierrebrd** [comment]
Thank you, I tested it and it works great ! 

The only weird thing is that after closing LTeX, I still see the "LTeX ready" in the status bar (I have the setting ltex.statusBarItem set to true), and when I start LTeX again using the "Check Current Document" command, it doesn't show "starting ltex", i only see "LTeX Ready" while java is starting and then "LTeX is checking " when java is ready and it starts checking the document. 
It is a really minor bug since it doesn't affect the behaviour of LTeX, so I don't think it really needs a fix.

![Screenshot From 2024-11-25 12-04-33](https://github.com/user-attachments/assets/635bd84e-20dd-42c3-aa77-996b406c8447)

**Comment by spitzerd** [comment]
I have no clue how to fix the status bar. As you said, it's not real issue.

**Comment by spitzerd** [comment]
The status bar issue is fixed now. You can test with the next nightly release.
