### ISSUE TITLE
Publish on Open VSX Registry

### ISSUE THREAD

**Issue by fph** [ltex-plus/vscode-ltex-plus#83]
Would it be possible to publish the extension also on https://open-vsx.org/ , so that it is available to [VSCodium](https://vscodium.com/) users?

**Comment by spitzerd** [comment]
I am working on it. Right now, I cannot continue due to https://github.com/eclipse/openvsx/issues/1032

**Comment by spitzerd** [comment]
It's published: https://open-vsx.org/extension/ltex-plus/vscode-ltex-plus
I requested the verification of the name space already: https://github.com/EclipseFdn/open-vsx.org/issues/3111

Also, I need to change ci.yml so that the next release is published automatically on Open VSX as well.
