### ISSUE TITLE
Support mdx File Type

### ISSUE THREAD

**Issue by alexandzors** [ltex-plus/vscode-ltex-plus#88]
Note: Per the contribution guidelines, deleting parts of the template or not filling in vital information may result in the issue to be immediately closed as invalid.

**Is your feature request related to a problem? Please describe.**
I use vscode to write blog posts in markdown since I find it much easier to do. I use LTeX with a locally hosted languagetool server and its been working well for awhile. However, I noticed the original extension was no longer updated and switched to this one. I also started using the mdx file format since my blog is being migrated to Astro. The problem I am having is that the extension no longer automatically starts when an mdx file is open, nor does it proof the file during editing. I have to manually start the extension on each launch of vscode and manually initiate a current file check after file changes.

**Describe the solution you'd like**
Would it be possible to have the extension recognize mdx as markdown so that it can work automatically?

**Describe alternatives you've considered**
I tried doing file type associations in vscode to have it detect mdx as markdown. However, that did not seem to fix it.

**Additional context**
N/A

**Comment by spitzerd** [comment]
Done. You can start testing tomorrow when a new nightly release is available.
